worker_processes 1;

events {
  worker_connections 1024;
}

http {
  sendfile on;

  upstream auth_service {
    server auth-service:8000;
  }

  upstream order_service {
    server order-service:8000;
  }

  upstream frontend {
    server frontend:5173;
  }

  server {
    listen 80;

    location /api/auth/ {
      proxy_pass http://auth_service/auth/;
      proxy_set_header X-Request-Id $request_id;
    }

    location /api/orders/ {
      proxy_pass http://order_service/orders/;
      proxy_set_header X-Request-Id $request_id;
    }

    location / {
      proxy_pass http://frontend;
    }
  }
}
